CUDA_VISIBLE_DEVICES=0 python run_textclass.py \
  --model_name_or_path Davlan/afro-xlmr-mini \
  --do_train \
  --do_eval \
  --do_predict \
  --per_device_train_batch_size 32 \
  --learning_rate 5e-5 \
  --num_train_epochs 1.0 \
  --max_seq_length 128 \
  --data_dir data/yor \
  --output_dir yor_sentiment \
  --save_steps -1
